import type { BufferGroup, TypedArray } from './geometries/buffer-geometry';
import {
  BufferAttribute,
  BufferGeometry,
  createBoxGeometry,
  createPlaneGeometry,
  createSphereGeometry,
} from './geometries';

import {
  Vector,
  Matrix,
  calculateSurfaceNormal,
  facesToBuffer,
  mix,
  clamp,
  Stopwatch,
  frustum,
  ortho,
  Mat2,
  Mat3,
  Mat4,
  Box3,
  Sphere,
  Quaternion,
  perspective,
  Color,
  mergeGeometries,
  createIndexedGeometry,
} from './utils';
import {
  Texture,
  Object3D,
  Scene,
  Camera,
  PerspectiveCamera,
  OrthographicCamera,
  Mesh,
  Light,
  AmbientLight,
  DirectionalLight,
  PointLight,
  NullRenderer,
  prepareScene,
  computeBoundingBox,
  computeBoundingSphere,
  Filter,
  Wrapping,
  DrawMode,
  ColorSpace,
  Side,
  AlphaMode,
  createBasicMaterial,
  createDefaultMaterial,
  createNormalMaterial,
  createShaderMaterial,
  createPbrMaterial,
} from './scene';
import type {
  Renderer,
  Frame,
  NullFrame,
  TextureData,
  TextureOptions,
  Material,
  PbrMap,
  PbrMaterialOptions,
  ShaderSource,
  Uniform,
  Uniforms,
} from './scene';
import { WebGL2Renderer, setUniform } from './webgl';
import type { LightUniforms } from './webgl';
import { loadGltf, parseGltf, parseGlb } from './loaders';
import type {
  GltfLoaderOptions,
  GltfResult,
  Glb,
  GltfAccessor,
  GltfAccessorType,
  GltfAlphaMode,
  GltfAsset,
  GltfBuffer,
  GltfBufferView,
  GltfCamera,
  GltfComponentType,
  GltfImage,
  GltfJson,
  GltfLight,
  GltfMaterial,
  GltfMesh,
  GltfNode,
  GltfNormalTextureInfo,
  GltfOcclusionTextureInfo,
  GltfOrthographicCamera,
  GltfPbrMetallicRoughness,
  GltfPerspectiveCamera,
  GltfPrimitive,
  GltfPrimitiveMode,
  GltfSampler,
  GltfScene,
  GltfSparseAccessor,
  GltfTexture,
  GltfTextureInfo,
} from './loaders';

export type {
  Renderer,
  Frame,
  NullFrame,
  Uniform,
  Uniforms,
  TextureData,
  TextureOptions,
  Material,
  PbrMap,
  PbrMaterialOptions,
  ShaderSource,
  BufferGroup,
  TypedArray,
  LightUniforms,
  GltfLoaderOptions,
  GltfResult,
  Glb,
  GltfAccessor,
  GltfAccessorType,
  GltfAlphaMode,
  GltfAsset,
  GltfBuffer,
  GltfBufferView,
  GltfCamera,
  GltfComponentType,
  GltfImage,
  GltfJson,
  GltfLight,
  GltfMaterial,
  GltfMesh,
  GltfNode,
  GltfNormalTextureInfo,
  GltfOcclusionTextureInfo,
  GltfOrthographicCamera,
  GltfPbrMetallicRoughness,
  GltfPerspectiveCamera,
  GltfPrimitive,
  GltfPrimitiveMode,
  GltfSampler,
  GltfScene,
  GltfSparseAccessor,
  GltfTexture,
  GltfTextureInfo,
};

export {
  BufferAttribute,
  BufferGeometry,
  createBoxGeometry,
  createPlaneGeometry,
  createSphereGeometry,
};
export {
  Texture,
  Object3D,
  Scene,
  Camera,
  PerspectiveCamera,
  OrthographicCamera,
  Mesh,
  Light,
  AmbientLight,
  DirectionalLight,
  PointLight,
  NullRenderer,
  WebGL2Renderer,
  prepareScene,
  computeBoundingBox,
  computeBoundingSphere,
  Filter,
  Wrapping,
  DrawMode,
  ColorSpace,
  Side,
  AlphaMode,
  createDefaultMaterial,
  createBasicMaterial,
  createNormalMaterial,
  createShaderMaterial,
  createPbrMaterial,
  setUniform,
};
export {
  Vector,
  Matrix,
  Color,
  Mat2,
  Mat3,
  Mat4,
  Box3,
  Sphere,
  Quaternion,
  calculateSurfaceNormal,
  facesToBuffer,
  mix,
  clamp,
  ortho,
  frustum,
  perspective,
  Stopwatch,
  mergeGeometries,
  createIndexedGeometry,
};
export { loadGltf, parseGltf, parseGlb };
